# Generated by Django 2.0.2 on 2018-04-18 14:11

from django.db import migrations, models
import topic.models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=topic.models.user_directory_path),
        ),
    ]
