# Generated by Django 2.0.2 on 2018-04-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20180418_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='click_num',
            new_name='comment_num',
        ),
        migrations.AddField(
            model_name='topic',
            name='goods_num',
            field=models.IntegerField(default=0),
        ),
    ]
