# Generated by Django 2.0.2 on 2018-04-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20180425_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='comment_num',
            new_name='comments_num',
        ),
    ]
