# Generated by Django 2.0.2 on 2018-04-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20180425_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(default='四川', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='成都', max_length=10),
        ),
    ]
